openapi: 3.0.1
info:
  x-logo:
    url: https://www.gridgain.com/assets/web/images/gridgain-logo-2021.svg
    backgroundColor: '#FFFFFF'
    altText: Example logo
  title: GridGain REST module authentication nodeManagement API
  contact:
    email: user@ignite.apache.org
  license:
    name: Apache 2.0
    url: https://ignite.apache.org
  version: 9.1.22
servers:
- url: http://localhost:10300
  description: Default GridGain 9 management API
- url: http://localhost:8080/ignite
  description: GridGain 8 / Ignite REST API
security:
- bearerToken: []
- basicAuth: []
tags:
- name: nodeManagement
paths:
  /management/v1/node/info:
    get:
      tags:
      - nodeManagement
      summary: Get node information
      description: Gets information about the node.
      operationId: nodeInfo
      responses:
        '200':
          description: Node info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInfo'
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/node/state:
    get:
      tags:
      - nodeManagement
      summary: Get node state
      description: Gets node state.
      operationId: nodeState
      responses:
        '200':
          description: Node state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeState'
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/node/version:
    get:
      tags:
      - nodeManagement
      summary: Get application version on node
      description: Gets the version of Apache Ignite the node uses.
      operationId: nodeVersion
      responses:
        '200':
          description: Node version.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/NodeVersion'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    State:
      type: string
      description: Possible node states.
      enum:
      - STARTING
      - STARTED
      - STOPPING
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          description: Parameter name.
        reason:
          type: string
          description: The issue with the parameter.
      description: Information about invalid request parameter.
    NodeInfo:
      required:
      - jdbcPort
      - name
      type: object
      properties:
        name:
          type: string
          description: Unique node name.
        jdbcPort:
          type: integer
          description: Node JDBC port.
          format: int32
      description: Node info.
    NodeVersion:
      required:
      - product
      - version
      type: object
      properties:
        version:
          type: string
          description: Node version.
        product:
          type: string
          description: Node product.
      description: Node version.
    NodeState:
      required:
      - name
      - state
      type: object
      properties:
        name:
          type: string
          description: Unique node name.
        state:
          allOf:
          - $ref: '#/components/schemas/State'
          - description: Node state.
      description: Node state.
    Problem:
      type: object
      properties:
        title:
          type: string
          description: Short summary of the issue.
        status:
          type: integer
          description: Returned HTTP status code.
          format: int32
        code:
          type: string
          description: Ignite 3 error code.
        type:
          type: string
          description: URI to documentation regarding the issue.
        detail:
          type: string
          description: Extended explanation of the issue.
        node:
          type: string
          description: Name of the node the issue happened on.
        traceId:
          type: string
          description: Unique issue identifier. This identifier can be used to find logs related to the issue.
          format: uuid
        invalidParams:
          type: array
          description: A list of parameters that did not pass validation and the reason for it.
          items:
            $ref: '#/components/schemas/InvalidParam'
      description: Extended description of the problem with the request.
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerToken:
      type: http
      scheme: bearer
