openapi: 3.0.1
info:
  x-logo:
    url: https://www.gridgain.com/assets/web/images/gridgain-logo-2021.svg
    backgroundColor: '#FFFFFF'
    altText: Example logo
  title: GridGain REST module authentication nodeMetric API
  contact:
    email: user@ignite.apache.org
  license:
    name: Apache 2.0
    url: https://ignite.apache.org
  version: 9.1.22
servers:
- url: http://localhost:10300
  description: Default GridGain 9 management API
- url: http://localhost:8080/ignite
  description: GridGain 8 / Ignite REST API
security:
- bearerToken: []
- basicAuth: []
tags:
- name: nodeMetric
paths:
  /management/v1/metric/node/disable:
    post:
      tags:
      - nodeMetric
      summary: Disable metric source
      description: Disables the specified metric source.
      operationId: disableNodeMetric
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Metric source disabled.
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Metric source not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/metric/node/enable:
    post:
      tags:
      - nodeMetric
      summary: Enable metric source
      description: Enables the specified metric source.
      operationId: enableNodeMetric
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Metric source enabled.
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Metric source not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/metric/node/set:
    get:
      tags:
      - nodeMetric
      summary: List metric sets
      description: Gets a list of all enabled metric sets.
      operationId: listNodeMetricSets
      responses:
        '200':
          description: Returned a list of metric sets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricSet'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/metric/node/source:
    get:
      tags:
      - nodeMetric
      summary: List metric sources
      description: Gets a list of all available metric sources.
      operationId: listNodeMetricSources
      responses:
        '200':
          description: Returned a list of metric sources.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricSource'
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    Metric:
      type: object
      properties:
        name:
          type: string
          description: Metric name.
        desc:
          type: string
          description: Metric description.
          nullable: true
      description: Metric representation.
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          description: Parameter name.
        reason:
          type: string
          description: The issue with the parameter.
      description: Information about invalid request parameter.
    Problem:
      type: object
      properties:
        title:
          type: string
          description: Short summary of the issue.
        status:
          type: integer
          description: Returned HTTP status code.
          format: int32
        code:
          type: string
          description: Ignite 3 error code.
        type:
          type: string
          description: URI to documentation regarding the issue.
        detail:
          type: string
          description: Extended explanation of the issue.
        node:
          type: string
          description: Name of the node the issue happened on.
        traceId:
          type: string
          description: Unique issue identifier. This identifier can be used to find logs related to the issue.
          format: uuid
        invalidParams:
          type: array
          description: A list of parameters that did not pass validation and the reason for it.
          items:
            $ref: '#/components/schemas/InvalidParam'
      description: Extended description of the problem with the request.
    MetricSource:
      required:
      - enabled
      - name
      type: object
      properties:
        name:
          type: string
          description: Metric source name.
        enabled:
          type: boolean
          description: If True, the metric is tracked. Otherwise, the metric is not tracked.
      description: A list of metric sources provided by modules.
    MetricSet:
      required:
      - metrics
      - name
      type: object
      properties:
        name:
          type: string
          description: Metric set name.
        metrics:
          type: array
          description: Metrics.
          items:
            $ref: '#/components/schemas/Metric'
      description: Metrics set representation.
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerToken:
      type: http
      scheme: bearer
