openapi: 3.0.1
info:
  x-logo:
    url: https://www.gridgain.com/assets/web/images/gridgain-logo-2021.svg
    backgroundColor: '#FFFFFF'
    altText: Example logo
  title: GridGain REST module authentication topology API
  contact:
    email: user@ignite.apache.org
  license:
    name: Apache 2.0
    url: https://ignite.apache.org
  version: 9.1.22
servers:
- url: http://localhost:10300
  description: Default GridGain 9 management API
- url: http://localhost:8080/ignite
  description: GridGain 8 / Ignite REST API
security:
- bearerToken: []
- basicAuth: []
tags:
- name: topology
paths:
  /management/v1/cluster/topology/logical:
    get:
      tags:
      - topology
      summary: Get logical topology
      description: Gets information about logical cluster topology.
      operationId: logical
      responses:
        '200':
          description: Logical topology returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClusterNode'
        '404':
          description: Logical topology not found. Most likely, the cluster is not initialized.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/cluster/topology/physical:
    get:
      tags:
      - topology
      summary: Get physical topology
      description: Gets information about physical cluster topology.
      operationId: physical
      responses:
        '200':
          description: Physical topology returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClusterNode'
        '500':
          description: Internal error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          description: Parameter name.
        reason:
          type: string
          description: The issue with the parameter.
      description: Information about invalid request parameter.
    ClusterNode:
      type: object
      properties:
        id:
          type: string
          description: Node ID.
          format: uuid
        name:
          type: string
          description: Unique cluster name.
        address:
          allOf:
          - $ref: '#/components/schemas/NetworkAddress'
          - description: Cluster network address information.
        metadata:
          allOf:
          - $ref: '#/components/schemas/NodeMetadata'
          - description: Node metadata information.
      description: Information about the cluster node.
    NetworkAddress:
      type: object
      properties:
        host:
          type: string
          description: Name of the host node runs on.
        port:
          type: integer
          description: Port the node runs on.
          format: int32
      description: Node network address information.
    Problem:
      type: object
      properties:
        title:
          type: string
          description: Short summary of the issue.
        status:
          type: integer
          description: Returned HTTP status code.
          format: int32
        code:
          type: string
          description: Ignite 3 error code.
        type:
          type: string
          description: URI to documentation regarding the issue.
        detail:
          type: string
          description: Extended explanation of the issue.
        node:
          type: string
          description: Name of the node the issue happened on.
        traceId:
          type: string
          description: Unique issue identifier. This identifier can be used to find logs related to the issue.
          format: uuid
        invalidParams:
          type: array
          description: A list of parameters that did not pass validation and the reason for it.
          items:
            $ref: '#/components/schemas/InvalidParam'
      description: Extended description of the problem with the request.
    NodeMetadata:
      type: object
      properties:
        restHost:
          type: string
          description: The host exposed to REST API.
        httpPort:
          type: integer
          description: The HTTP port exposed to REST API.
          format: int32
        httpsPort:
          type: integer
          description: The HTTPS port exposed to REST API.
          format: int32
      description: Node metadata information.
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerToken:
      type: http
      scheme: bearer
