openapi: 3.0.1
info:
  x-logo:
    url: https://www.gridgain.com/assets/web/images/gridgain-logo-2021.svg
    backgroundColor: '#FFFFFF'
    altText: Example logo
  title: GridGain REST module authentication compute API
  contact:
    email: user@ignite.apache.org
  license:
    name: Apache 2.0
    url: https://ignite.apache.org
  version: 9.1.22
servers:
- url: http://localhost:10300
  description: Default GridGain 9 management API
- url: http://localhost:8080/ignite
  description: GridGain 8 / Ignite REST API
security:
- bearerToken: []
- basicAuth: []
tags:
- name: compute
paths:
  /management/v1/compute/jobs:
    get:
      tags:
      - compute
      summary: Retrieve all job states
      description: Fetches the current states of all compute jobs.
      operationId: jobStates
      responses:
        '200':
          description: Successfully retrieved job states.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobState'
        '503':
          description: Missing license error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/compute/jobs/{jobId}:
    get:
      tags:
      - compute
      summary: Retrieve job state
      description: Fetches the current state of a specific compute job identified by jobId.
      operationId: jobState
      parameters:
      - name: jobId
        in: path
        description: The unique identifier of the compute job.
        required: true
        schema:
          type: string
          description: The unique identifier of the compute job.
          format: uuid
      responses:
        '200':
          description: Successfully retrieved the job state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobState'
        '404':
          description: Compute job not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '503':
          description: Missing license error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      tags:
      - compute
      summary: Cancel job
      description: Cancels a specific compute job identified by jobId.
      operationId: cancelJob
      parameters:
      - name: jobId
        in: path
        description: The unique identifier of the compute job.
        required: true
        schema:
          type: string
          description: The unique identifier of the compute job.
          format: uuid
      responses:
        '200':
          description: Successfully cancelled the job.
          content:
            application/json: {}
        '404':
          description: Compute job not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Compute job is in an illegal state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '503':
          description: Missing license error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /management/v1/compute/jobs/{jobId}/priority:
    put:
      tags:
      - compute
      summary: Update job priority
      description: Updates the priority of a specific compute job identified by jobId.
      operationId: updatePriority
      parameters:
      - name: jobId
        in: path
        description: The unique identifier of the compute job.
        required: true
        schema:
          type: string
          description: The unique identifier of the compute job.
          format: uuid
      requestBody:
        description: The new priority data for the job.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobPriorityBody'
        required: true
      responses:
        '200':
          description: Successfully updated job priority.
          content:
            application/json: {}
        '404':
          description: Compute job not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Compute job is in an illegal state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '503':
          description: Missing license error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          description: Parameter name.
        reason:
          type: string
          description: The issue with the parameter.
      description: Information about invalid request parameter.
    Problem:
      type: object
      properties:
        title:
          type: string
          description: Short summary of the issue.
        status:
          type: integer
          description: Returned HTTP status code.
          format: int32
        code:
          type: string
          description: Ignite 3 error code.
        type:
          type: string
          description: URI to documentation regarding the issue.
        detail:
          type: string
          description: Extended explanation of the issue.
        node:
          type: string
          description: Name of the node the issue happened on.
        traceId:
          type: string
          description: Unique issue identifier. This identifier can be used to find logs related to the issue.
          format: uuid
        invalidParams:
          type: array
          description: A list of parameters that did not pass validation and the reason for it.
          items:
            $ref: '#/components/schemas/InvalidParam'
      description: Extended description of the problem with the request.
    UpdateJobPriorityBody:
      required:
      - priority
      type: object
      properties:
        priority:
          type: integer
          description: Priority.
          format: int32
      description: DTO of update job priority request body.
    JobState:
      required:
      - createTime
      - id
      - status
      type: object
      properties:
        id:
          type: string
          description: Job ID.
          format: uuid
        status:
          description: Job status.
          allOf:
          - $ref: '#/components/schemas/JobStatus'
          - {}
        createTime:
          type: string
          description: Job create time.
          format: date-time
        startTime:
          type: string
          description: Job start time.
          format: date-time
          nullable: true
        finishTime:
          type: string
          description: Job finish time.
          format: date-time
          nullable: true
      description: Rest representation of org.apache.ignite.compute.JobState.
    JobStatus:
      type: string
      description: Job status.
      enum:
      - QUEUED
      - EXECUTING
      - FAILED
      - COMPLETED
      - CANCELING
      - CANCELED
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerToken:
      type: http
      scheme: bearer
