openapi: 3.0.1
info:
  x-logo:
    url: https://www.gridgain.com/assets/web/images/gridgain-logo-2021.svg
    backgroundColor: '#FFFFFF'
    altText: Example logo
  title: GridGain REST module authentication sql API
  contact:
    email: user@ignite.apache.org
  license:
    name: Apache 2.0
    url: https://ignite.apache.org
  version: 9.1.22
servers:
- url: http://localhost:10300
  description: Default GridGain 9 management API
- url: http://localhost:8080/ignite
  description: GridGain 8 / Ignite REST API
security:
- bearerToken: []
- basicAuth: []
tags:
- name: sql
paths:
  /management/v1/sql/plan/clear-cache:
    get:
      tags:
      - sql
      summary: Invalidates SQL planner cache.
      description: Invalidates SQL planner cache records on node that related to provided table names.
      operationId: clearCache
      parameters:
      - name: tableNames
        in: query
        schema:
          type: array
          description: SQL query plans, which are related to given tables, will be evicted from cache. Case-sensitive, cache will be reset if empty.
          nullable: true
          items:
            type: string
      responses:
        '200':
          description: Successfully cleared SQL query plan cache.
  /management/v1/sql/queries:
    get:
      tags:
      - sql
      summary: Retrieve all running sql queries.
      description: Fetches all running sql queries.
      operationId: queries
      responses:
        '200':
          description: Successfully retrieved all running sql queries.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SqlQuery'
  /management/v1/sql/queries/{queryId}:
    get:
      tags:
      - sql
      summary: Retrieve sql query.
      description: Fetches the current state of a specific sql query.
      operationId: query
      parameters:
      - name: queryId
        in: path
        description: The unique identifier of the sql query.
        required: true
        schema:
          type: string
          description: The unique identifier of the sql query.
          format: uuid
      responses:
        '200':
          description: Successfully retrieved the sql query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SqlQuery'
        '404':
          description: Query not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      tags:
      - sql
      summary: Kill sql query.
      description: Kills a specific sql query identified by query id.
      operationId: killQuery
      parameters:
      - name: queryId
        in: path
        description: The unique identifier of the sql query.
        required: true
        schema:
          type: string
          description: The unique identifier of the sql query.
          format: uuid
      responses:
        '200':
          description: Successfully killed the sql query.
          content:
            application/json: {}
        '404':
          description: Query not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Query is in an illegal state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    Problem:
      type: object
      properties:
        title:
          type: string
          description: Short summary of the issue.
        status:
          type: integer
          description: Returned HTTP status code.
          format: int32
        code:
          type: string
          description: Ignite 3 error code.
        type:
          type: string
          description: URI to documentation regarding the issue.
        detail:
          type: string
          description: Extended explanation of the issue.
        node:
          type: string
          description: Name of the node the issue happened on.
        traceId:
          type: string
          description: Unique issue identifier. This identifier can be used to find logs related to the issue.
          format: uuid
        invalidParams:
          type: array
          description: A list of parameters that did not pass validation and the reason for it.
          items:
            $ref: '#/components/schemas/InvalidParam'
      description: Extended description of the problem with the request.
    SqlQuery:
      required:
      - id
      - node
      - phase
      - schema
      - sql
      - startTime
      - type
      type: object
      properties:
        id:
          type: string
          description: Sql query ID.
          format: uuid
        node:
          type: string
          description: Initiator node.
        phase:
          type: string
          description: Phase.
        type:
          type: string
          description: Type.
        schema:
          type: string
          description: Schema.
        sql:
          type: string
          description: SQL statement.
        startTime:
          type: string
          description: Start time.
          format: date-time
      description: Rest representation of sql query.
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          description: Parameter name.
        reason:
          type: string
          description: The issue with the parameter.
      description: Information about invalid request parameter.
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerToken:
      type: http
      scheme: bearer
